name: Github Actions Demo
on: 
  push:
    branches: main
    paths-ignore: .github/**
  schedule:
    - cron: '15 6 * * SUN'
  pull_request:
    branches: main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to deploy to'

jobs:
  Build:
   runs-on: ubuntu-latest   
   steps:
     - name: Display event
       run: echo "${{ github.event_name }}"       
     
     - name: Display branch
       run: echo "${{ github.ref_name }}"
       
     - name: List files
       run: ls -alh       
 
  Testing:
    name: "Testing"
    runs-on: ubuntu-latest
    environment: Test
    needs: [Build]
    if: github.event == 'workflow_dispatch'
    steps:
    - run: echo "Testing..."
    
  LoadTesting:
    name: "Load Testing"
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: [Build]
    if: github.event == 'workflow_dispatch'
    steps:
    - run: |
        echo "Testing..."
        sleep 15
        
  Deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://writeabout.net
    needs: [Testing, LoadTesting]
    if: github.event.inputs.environment == 'Production'
    steps:
    - run: |
        echo "Step 1 deploying..."
        sleep 10
    - run: |
        echo "Step 2 deploying..."
        sleep 10
    - run: |
        echo "Step 3 deploying..."
        sleep 10
    - run: |
        echo "Step 4 deploying..."
        sleep 10
    - run: |
        echo "Step 5 deploying..."
        sleep 10        
        
        
