name: Hello World Docker
on: [ workflow_dispatch ]
jobs:
  Run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        
      - name: Run container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@JonathanAyling'
          
      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
